// Code generated by Kitex v0.9.1. DO NOT EDIT.

package testservice

import (
	"context"
	"errors"
	test "github.com/YiD11/gomall/rpc_gen/kitex_gen/test"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PrintTest": kitex.NewMethodInfo(
		printTestHandler,
		newPrintTestArgs,
		newPrintTestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	testServiceServiceInfo                = NewServiceInfo()
	testServiceServiceInfoForClient       = NewServiceInfoForClient()
	testServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return testServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return testServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return testServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TestService"
	handlerType := (*test.TestService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "test",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func printTestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(test.TestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(test.TestService).PrintTest(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PrintTestArgs:
		success, err := handler.(test.TestService).PrintTest(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PrintTestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPrintTestArgs() interface{} {
	return &PrintTestArgs{}
}

func newPrintTestResult() interface{} {
	return &PrintTestResult{}
}

type PrintTestArgs struct {
	Req *test.TestReq
}

func (p *PrintTestArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(test.TestReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PrintTestArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PrintTestArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PrintTestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PrintTestArgs) Unmarshal(in []byte) error {
	msg := new(test.TestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PrintTestArgs_Req_DEFAULT *test.TestReq

func (p *PrintTestArgs) GetReq() *test.TestReq {
	if !p.IsSetReq() {
		return PrintTestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PrintTestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PrintTestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PrintTestResult struct {
	Success *test.TestResp
}

var PrintTestResult_Success_DEFAULT *test.TestResp

func (p *PrintTestResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(test.TestResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PrintTestResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PrintTestResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PrintTestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PrintTestResult) Unmarshal(in []byte) error {
	msg := new(test.TestResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PrintTestResult) GetSuccess() *test.TestResp {
	if !p.IsSetSuccess() {
		return PrintTestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PrintTestResult) SetSuccess(x interface{}) {
	p.Success = x.(*test.TestResp)
}

func (p *PrintTestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PrintTestResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PrintTest(ctx context.Context, Req *test.TestReq) (r *test.TestResp, err error) {
	var _args PrintTestArgs
	_args.Req = Req
	var _result PrintTestResult
	if err = p.c.Call(ctx, "PrintTest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
