name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: check docker
      run: docker version
      
    - name: build services
      run: make build-all v=latest
    - name: start cluster
      run: docker compose -f ./cluster.docker-compose.yml up -d
    - name: Wait for cluster to be ready
      run: |
        echo "Waiting for cluster to start..."
        sleep 5
        
    - name: start service
      run: VERSION=latest docker compose -f ./app.docker-compose.yml up -d
    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to start..."
        sleep 10
        
    - name: test browse products
      run: |
        for i in {1..10}; do
          curl -s http://localhost:8090/about && break
          echo "Waiting for service to start..."
          sleep 5
        done
